version: '3.1'

services:
  test-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=postgres
    restart: on-failure

  tests:
    command: ./wait-for-it.sh test-db:5432 -- ./run-tests.sh
    build:
      context: .
      dockerfile: app.Dockerfile
    depends_on:
      - "test-db"
      

